name: island_slide_puzzle
description: A floating slide puzzle from the Netherlands.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.20
  platform: ^3.1.0
  rive: ^0.8.1
  url_launcher: ^6.0.20

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  msix: ^3.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/downloads/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic

msix_config:
  display_name: Island Slide Puzzle
  publisher_display_name: ReneFloor Software Development
  identity_name: 5515ReneFloorSoftwareDeve.IslandSlidePuzzle
  msix_version: 0.0.3.0
  publisher: CN=337FF815-4DE7-4305-890E-947FA235BAF9
  store: true
  logo_path: ./windows/app_icon.png
  capabilities: internetClient