name: Build Snap store

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "assets/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "linux/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge