name: Build Android store

on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: macos-latest
    name: Build Android app
    env:
      ANDROID_KEYSTORE_PATH: ../island-puzzle.jks
      ANDROID_KEYSTORE_ALIAS: upload
      ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PW }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PW }}
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.10.0
          channel: stable

      - name: Install Dependencies
        run: flutter packages get
      - name: Download keystore
        run: curl https://${{ secrets.REPO_ACCESS_TOKEN }}@raw.githubusercontent.com/renefloor/flutter_puzzle_hack_secrets/main/island-puzzle.jks -o android/island-puzzle.jks

      - name: Build for android
        run: |
          flutter build appbundle \
          --build-number $GITHUB_RUN_NUMBER

      - uses: actions/upload-artifact@v1
        with:
          name: android-test-build
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload app bundle to Google Play
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: nl.renefloor.puzzle
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          mappingFile: build/app/outputs/mapping/release/mapping.txt