name: Build Microsoft store

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "windows/**"
    branches:
      - master


jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows app
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.10.0
          channel: stable

      - name: Enable windows
        run: flutter config --enable-windows-desktop
        working-directory: ${{env.source-directory}}

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for windows
        run: flutter pub run msix:create

      - uses: isaacrlevin/windows-store-action@1.0
        name: Publish to Store
        with:
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
          app-id: ${{ secrets.WINDOWS_STORE_APP_ID }}
          package-path: build\windows\runner\Release\island_slide_puzzle.msix
