name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build macOS app
    if: ${{ false }}  # disable for now
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.10.0
          channel: stable

      - name: Enable macOS
        run: flutter config --enable-macos-desktop
        working-directory: ${{env.source-directory}}

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for mac
        run: |
          flutter build macos \
          --build-number $GITHUB_RUN_NUMBER

      - name: Create a dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg
          
          cd $MACOS_APP_RELEASE_PATH
          
          create-dmg \
            "slide_puzzle.dmg" \
            "slide_puzzle.app"

      - uses: actions/upload-artifact@v1
        with:
          name: macos-test-build
          path: build/macos/Build/Products/Release/slide_puzzle.dmg

  build-windows:
    runs-on: windows-latest
    name: Build Windows app
#    if: ${{ false }}  # disable for now
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.10.0
          channel: stable

      - name: Enable windows
        run: flutter config --enable-windows-desktop
        working-directory: ${{env.source-directory}}

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for windows
        run: flutter pub run msix:create

      - uses: actions/upload-artifact@v1
        with:
          name: windows-test-build
          path: build\windows\runner\Release\island_slide_puzzle.msix

  deploy:
    runs-on: ubuntu-latest
    name: deploy
    if: ${{ false }}  # disable for now

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.10.0
          channel: stable

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for Web
        run: flutter build web

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLIDE_PUZZLE_1A294 }}'
          channelId: live
          projectId: slide-puzzle-1a294
